name: complex file

on:
  push:
    branches: [main]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date

  mac-os:
    runs-on: macos-latest
    steps:
    - run: date

  windows:
    runs-on: windows-latest
    steps:
    - run: date

  depends:
    needs: [ubuntu, mac-os, windows]
    runs-on: macos-latest
    steps:
    - run: date
